<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="Mocha Tests" time="6.8460" tests="1" failures="1">
  <testsuite name="Root Suite" timestamp="2020-08-19T06:38:28" tests="0" file="cypress\integration\secondTest.spec.js" time="0.0000" failures="0">
  </testsuite>
  <testsuite name="Test log out" timestamp="2020-08-19T06:38:28" tests="1" time="6.8460" failures="1">
    <testcase name="Test log out verify logging out" time="6.8460" classname="verify logging out">
      <failure message="Timed out retrying: expected &apos;&lt;ul.nav.navbar-nav.pull-xs-right&gt;&apos; to contain &apos;Sign in1&apos;" type="AssertionError"><![CDATA[AssertionError: Timed out retrying: expected '<ul.nav.navbar-nav.pull-xs-right>' to contain 'Sign in1'
    at Context.eval (http://localhost:4200/__cypress/tests?p=cypress\integration\secondTest.spec.js:9:58)]]></failure>
    </testcase>
  </testsuite>
</testsuites>